#!/bin/bash
declare -A md_cpt
# md_cpt=( ["RN50"]="clip_cn_rn50.pt" ["ViT-B-16"]="clip_cn_vit-b-16.pt" ["ViT-H-14"]="clip_cn_vit-h-14.pt" ["ViT-L-14-336"]="clip_cn_vit-l-14-336.pt" ["ViT-L-14"]="clip_cn_vit-l-14.pt" )
md_cpt=( ["ViT-H-14"]="clip_cn_vit-h-14.pt" )
# export CUDA_VISIBLE_DEVICES=0
 export PYTHONPATH=${PYTHONPATH}:/home/featurize/work/Chinese-CLIP/cn_clip

DATAPATH=/home/featurize/work
split=valid # 指定计算valid或test集特征
dataset_name=railway
cpt='clip_cn_rn50.pt  clip_cn_vit-b-16.pt  clip_cn_vit-h-14.pt  clip_cn_vit-l-14-336.pt  clip_cn_vit-l-14.pt'
# models="ViT-B-32", "ViT-B-16", "ViT-L-14", "ViT-L-14-336", "ViT-H-14", "RN50"
# models='RN50 ViT-B-16 ViT-H-14 ViT-L-14-336 ViT-L-14'
models='RN50 ViT-B-16 ViT-H-14 ViT-L-14-336 ViT-L-14'
# md_cpt=(
# 	'RN50::clip_cn_rn50.pt'
# 	'ViT-B-16::clip_cn_vit-b-16.pt'
# 	'ViT-H-14::clip_cn_vit-h-14.pt'
# 	'ViT-L-14-336::clip_cn_vit-l-14-336.pt'
# 	'ViT-L-14::clip_cn_vit-l-14.pt'
# )



	# md="${index%%::*}"
	# pt="${index##*::}"
	md=epoch2
	pt=epoch2.pt
  resume=/home/featurize/data/experiments/muge_finetune_vit-l-14-336_roberta-base_bs128_1gpu/checkpoints/$pt
 	python -u /home/featurize/work/Chinese-CLIP/cn_clip/eval/extract_features.py \
     --extract-image-feats \
     --extract-text-feats \
     --image-data="${DATAPATH}/datasets/${dataset_name}/lmdb/${split}/imgs" \
     --text-data="${DATAPATH}/datasets/${dataset_name}/${split}_texts.jsonl" \
     --img-batch-size=32 \
     --text-batch-size=32 \
     --context-length=52 \
     --resume=${resume} \
     --vision-model=ViT-L-14-336 \
     --text-model=RoBERTa-wwm-ext-base-chinese \
 	  --image-feat-output-path="${DATAPATH}/datasets/${dataset_name}/${md}_${split}.img_feat.jsonl"\
 	  --text-feat-output-path="${DATAPATH}/datasets/${dataset_name}/${md}_${split}.txt_feat.jsonl"
	 
